version: '3'
services:
  nginx:
    depends_on:
      - api
    build: ./nginx
    restart: always
    ports:
      - 80:80
  api:
    build: ./api
    environment:
      - DATABASE_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}



